server:
  port: 8080
  application:
    name: ProductService
    version: 1.0
    description: Product Service for Online Shopping

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true